package cn.succy.chat.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setAid(java.lang.Integer aid) {
		set("aid", aid);
		return (M)this;
	}

	public java.lang.Integer getAid() {
		return get("aid");
	}

	public M setNickname(java.lang.String nickname) {
		set("nickname", nickname);
		return (M)this;
	}

	public java.lang.String getNickname() {
		return get("nickname");
	}

	public M setPwd(java.lang.String pwd) {
		set("pwd", pwd);
		return (M)this;
	}

	public java.lang.String getPwd() {
		return get("pwd");
	}

	public M setRegion(java.lang.String region) {
		set("region", region);
		return (M)this;
	}

	public java.lang.String getRegion() {
		return get("region");
	}

	public M setSignature(java.lang.String signature) {
		set("signature", signature);
		return (M)this;
	}

	public java.lang.String getSignature() {
		return get("signature");
	}

	public M setGender(java.lang.Boolean gender) {
		set("gender", gender);
		return (M)this;
	}

	public java.lang.Boolean getGender() {
		return get("gender");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setIsLogin(java.lang.Boolean isLogin) {
		set("is_login", isLogin);
		return (M)this;
	}

	public java.lang.Boolean getIsLogin() {
		return get("is_login");
	}

}
